### ISSUE TITLE
Improvement on documentation 

### ISSUE THREAD

**Issue by crossedheadx** [PNZdevs/trippal-ionic-vue#1]
On point 1 in readme, this element:

> 
> **1. Create directories:**
> 
> ```
> $ sudo mkdir /usr/local/android-studio  
> $ sudo mkdir /usr/local/android-studio/bin
> ```
> 

can be shortened as:

> 
> **1. Create directories:**
> 
> ```
> # mkdir -p  /usr/local/android-studio/bin
> ```
> 

The ```mkdir -p``` means the target folder will be created with the missing parent folder, so the ```android-studio``` folder will be created together ```bin```. 
Also, use ```sudo``` is not a wrong suggestion, but, consider first to indicate this action as a root user (using #, instead $), after suggest ```$ sudo command``` to help newcomers. :wink:

**Comment by andreapozza** [comment]
https://github.com/PNZdevs/trippal-ionic-vue/commit/260c60cebad18bfd5f6a6b82b76d82d271536585

**Comment by andreapozza** [comment]
Updated! Thanks :)
https://github.com/PNZdevs/trippal-ionic-vue/commit/260c60cebad18bfd5f6a6b82b76d82d271536585
